name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ACTION:
        description: 'Terragrunt Action (plan/apply)'
        required: true
        default: 'plan'

env:
  AWS_REGION: eu-west-1

jobs:
  Terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5
          terraform_wrapper: false

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip jq
          pip3 install --upgrade pip
          pip3 install --no-cache-dir awscli
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.53.2/terragrunt_linux_amd64
          mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      - name: Terragrunt Init
        run: |
          terragrunt init --terragrunt-non-interactive --terragrunt-working-dir env/testing

      - name: Terragrunt Plan
        run: |
          terragrunt plan --terragrunt-non-interactive --terragrunt-working-dir env/testing

      - name: Terragrunt Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.ACTION == 'apply'
        run: |
          terragrunt apply --terragrunt-non-interactive --terragrunt-working-dir env/testing
