name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      ACTION:
        description: 'Action to take'
        required: true
        default: 'init'
        type: choice
        options:
          - init
          - plan
          - apply
      ENV:
        description: 'Environment to deploy'
        required: true
        default: 'testing'
        type: choice
        options:
          - staging
          - testing
          - production
      AWS_REGION:
        description: 'AWS region'
        required: true
        default: 'eu-west-1'
        type: choice
        options:
          - eu-west-1
      ENVIRONMENT_DIRECTORY:
        description: 'Environment directory'
        required: true
        default: 'env/testing'
        type: choice
        options:
          - env/staging
          - env/testing
          - env/production

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip jq
          pip3 install --upgrade pip
          pip3 install --no-cache-dir awscli
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.53.2/terragrunt_linux_amd64
          mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity  # Check if authentication is successful

      - name: Terraform Init
        run: |
          terragrunt init --terragrunt-working-dir ${{ github.workspace }}/${{ inputs.ENVIRONMENT_DIRECTORY }}/${{ inputs.AWS_REGION }}
          # terragrunt init --terragrunt-working-dir ${{ github.workspace }}/env/staging/eu-west-1

      - name: Terraform Plan
        run: |
          terragrunt plan --terragrunt-working-dir ${{ github.workspace }}/${{ inputs.ENVIRONMENT_DIRECTORY }}/${{ inputs.AWS_REGION }}

      - name: Terraform Apply (if applicable)
        if: ${{ inputs.ACTION == 'apply' }}
        run: |
          terragrunt apply --terragrunt-working-dir ${{ github.workspace }}/${{ inputs.ENVIRONMENT_DIRECTORY }}/${{ inputs.AWS_REGION }}
